version: '3.8'

services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      # Montamos todo tu proyecto local dentro del contenedor para que los cambios se reflejen al instante
      - .:/workspace
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='basket'
